# -*- coding: utf-8 -*-
"""pd4760_ML1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VFVSyYTTUzl8zYI6IHJRGk68lyM2d0Fp
"""

import pandas as pd

df = pd.read_csv("/content/dane_projekt1.csv")
print(df.describe())
print(df.head())

from sklearn.model_selection import train_test_split

X = df.drop(columns=["Gene_Function"])
y = df["Gene_Function"]

# X_temp - tymczasowa zmienna, ktora przechowuje dane przed kolejnym podzialem
# X_test - zbior danych testowych
X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# Podzial 80% danych z X_temp na dane treningowe i walidacyjne
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.25, stratify=y_temp, random_state=42)